/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uzdevumi;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Skaitlis = new javax.swing.JTextField();
        SkaitlaApstrade = new javax.swing.JButton();
        SkaitlaIzvade = new javax.swing.JLabel();
        Reste = new javax.swing.JTextField();
        RestesApstrade = new javax.swing.JButton();
        RestesIzvade = new javax.swing.JLabel();
        Teksts = new javax.swing.JTextField();
        TekstaApstrade = new javax.swing.JButton();
        TekstaIzvade = new javax.swing.JLabel();

        SkaitlaApstrade.setText("=>");
        SkaitlaApstrade.setToolTipText("");
        SkaitlaApstrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkaitlaApstradeActionPerformed(evt);
            }
        });

        RestesApstrade.setText("=>");
        RestesApstrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestesApstradeActionPerformed(evt);
            }
        });

        TekstaApstrade.setText("=>");
        TekstaApstrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TekstaApstradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Teksts, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(Reste)
                    .addComponent(Skaitlis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SkaitlaApstrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RestesApstrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TekstaApstrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SkaitlaIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(RestesIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TekstaIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SkaitlaApstrade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Skaitlis)
                    .addComponent(SkaitlaIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestesApstrade, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestesIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Teksts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TekstaApstrade)
                    .addComponent(TekstaIzvade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(188, 188, 188))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SkaitlaApstradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkaitlaApstradeActionPerformed
        // TODO add your handling code here:
        
         String skaitlis = Skaitlis.getText();
        
        if (skaitlis.matches(".*[a-zA-Z]+.*")){
            SkaitlaIzvade.setText("Ievadītā vērtība nav skaitlis");
        }
        
        int cipari = Integer.parseInt(skaitlis);

        if (cipari > 5){
            SkaitlaIzvade.setText("Skaitlis ir lielāks par 5");
        }else if ( cipari == 5) {
            SkaitlaIzvade.setText("Skaitlis ir vienāds ar 5");
        }else if (cipari < 5){
            SkaitlaIzvade.setText("Skaitlis ir mazāks par 5");
        }
            
    }//GEN-LAST:event_SkaitlaApstradeActionPerformed

    private void RestesApstradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestesApstradeActionPerformed
        // TODO add your handling code here:
        
        String reste = Reste.getText();
        
        int skaits = Integer.parseInt(reste);
        
        for (int i=0; i < 10; i++){
            RestesIzvade.setText(String.valueOf("#"));
        }
        
        
       
    }//GEN-LAST:event_RestesApstradeActionPerformed

    private void TekstaApstradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TekstaApstradeActionPerformed
        // TODO add your handling code here:
        
           String teksts = Teksts.getText();
        
        if( teksts.charAt(0) == teksts.toUpperCase().charAt(0)){
            TekstaIzvade.setText(teksts.toUpperCase());
        }else{
            TekstaIzvade.setText("Ievadi vārdu ar lielo burtu");
        }
    }//GEN-LAST:event_TekstaApstradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Reste;
    private javax.swing.JButton RestesApstrade;
    private javax.swing.JLabel RestesIzvade;
    private javax.swing.JButton SkaitlaApstrade;
    private javax.swing.JLabel SkaitlaIzvade;
    private javax.swing.JTextField Skaitlis;
    private javax.swing.JButton TekstaApstrade;
    private javax.swing.JLabel TekstaIzvade;
    private javax.swing.JTextField Teksts;
    // End of variables declaration//GEN-END:variables
}
