/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diena9;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputButton = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        InputLogin = new javax.swing.JTextField();
        Aiziet = new javax.swing.JButton();
        InputPassword = new javax.swing.JTextField();

        InputButton.setText("Ievadi lietotājvārdu un paroli");
        InputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputButtonActionPerformed(evt);
            }
        });

        InputLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputLoginActionPerformed(evt);
            }
        });

        Aiziet.setText("Aiziet");
        Aiziet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AizietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aiziet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputButton))
                                .addGap(0, 209, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(InputButton)
                .addGap(27, 27, 27)
                .addComponent(InputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Aiziet)
                    .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputButtonActionPerformed
        // TODO add your handling code here:
        String currentText = InputLogin.getText();
        
//        if(currentText.length() > 5 ){
//            Label.setText(currentText.toUpperCase());
//            
//        }else{
//            Label.setText(currentText);
//        }  

//        if (currentText.contains(" ")){
//            Label.setText(currentText.replace(" ", ""));
//        }else{
//            Label.setText(currentText);
//        }
        
            //currentText.contain, 
//        if (currentText.equals("")){
//            Label.setText(currentText.replace("a", "b"));
//            Label.setText(currentText.toUpperCase());
//            Label.setText("Kluda");
            
// replace
// Ja ievades lauks ir tukšs - parādām, ka ir kļūda
// Ja vārdā ir vairāk par 5 simboliem, tad pārveidojam uz vārdu ar lielajiem burtiem
// Ja cilvēka ievadē ir " " (space), tad to aizvakt
       
// Logins un parole
// Pēc pogas nospiešanas vai abi lauki ir aizpildīti
// Vai abos laukos simbolu skaits ir > 5
// Vai paroles laukā ir gan burti, gan cipari
// vai logina pirmais burts ir lielais burts- s.charAt(i)
// Vai logina laukā nav vārda "DROP"
        
        if (currentText.equals("")){
            Label.setText("Kļūda");
        }


    }//GEN-LAST:event_InputButtonActionPerformed

    private void InputLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLoginActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_InputLoginActionPerformed

    private void AizietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AizietActionPerformed
        // TODO add your handling code here:
         String login = InputLogin.getText();
         String password = InputLogin.getText();
         
          if (login.equals("") || password.equals("")){
            Label.setText("Lietotājvards vai parole nav pareiza");
          }else {
              Label.setText("Veiksmīgi");
          }
          if (login.length()< 5 || password.length() < 5){
              Label.setText("Lietotājvards vai parole nav pareiza");
          }else {
              Label.setText("Veiksmīgi");
          }
          if (password.matches(".*\\d+.*")){
              Label.setText("Veiksmīgi");
          }else{
              Label.setText("Lietotājvards vai parole nav pareiza");
          }
//          for (int i=0; i< login.length(); i++){
//              char c = login.charAt(i);
//             
//          }
          
    }//GEN-LAST:event_AizietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aiziet;
    private javax.swing.JButton InputButton;
    private javax.swing.JTextField InputLogin;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JLabel Label;
    // End of variables declaration//GEN-END:variables
}
