/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diena7_package;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JPanel {
    
    String pirmaisSkaitlis;
    String zime = "";
    boolean darbiba = false;
    
    
    

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poga1 = new javax.swing.JButton();
        poga2 = new javax.swing.JButton();
        poga3 = new javax.swing.JButton();
        poga7 = new javax.swing.JButton();
        poga6 = new javax.swing.JButton();
        poga4 = new javax.swing.JButton();
        poga8 = new javax.swing.JButton();
        poga5 = new javax.swing.JButton();
        poga9 = new javax.swing.JButton();
        poga0 = new javax.swing.JButton();
        Laukums = new javax.swing.JLabel();
        pogaequal = new javax.swing.JButton();
        pogaplus = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Kapinasana = new javax.swing.JButton();

        poga1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga1.setText("1");
        poga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga1ActionPerformed(evt);
            }
        });

        poga2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga2.setText("2");
        poga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga2ActionPerformed(evt);
            }
        });

        poga3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga3.setText("3");
        poga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga3ActionPerformed(evt);
            }
        });

        poga7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga7.setText("7");
        poga7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga7ActionPerformed(evt);
            }
        });

        poga6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga6.setText("6");
        poga6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga6ActionPerformed(evt);
            }
        });

        poga4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga4.setText("4");
        poga4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga4ActionPerformed(evt);
            }
        });

        poga8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga8.setText("8");
        poga8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga8ActionPerformed(evt);
            }
        });

        poga5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga5.setText("5");
        poga5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga5ActionPerformed(evt);
            }
        });

        poga9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga9.setText("9");
        poga9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga9ActionPerformed(evt);
            }
        });

        poga0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        poga0.setText("0");
        poga0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poga0ActionPerformed(evt);
            }
        });

        Laukums.setText("0");

        pogaequal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pogaequal.setText("=");
        pogaequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogaequalActionPerformed(evt);
            }
        });

        pogaplus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pogaplus.setText("+");
        pogaplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogaplusActionPerformed(evt);
            }
        });

        Minus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Clear.setText("CE");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Kapinasana.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kapinasana.setText("^");
        Kapinasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapinasanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poga4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poga1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(poga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poga5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(poga7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poga8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poga0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(poga9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(poga6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(poga3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pogaequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pogaplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Kapinasana))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Laukums, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poga1)
                    .addComponent(poga2)
                    .addComponent(poga3)
                    .addComponent(pogaplus))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poga4)
                    .addComponent(poga5)
                    .addComponent(poga6)
                    .addComponent(Minus))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poga7)
                    .addComponent(poga8)
                    .addComponent(poga9)
                    .addComponent(Kapinasana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pogaequal)
                    .addComponent(poga0)
                    .addComponent(Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Laukums, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SkaitluParadisana(String poga){
        
        String currentText = Laukums.getText();
        if(currentText.equals("0") || currentText.equals("+") || currentText.equals("-") || currentText.equals("^")){
            currentText = "";
        }
        Laukums.setText(currentText + poga);
    }
    
    private void poga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga1ActionPerformed
        
        SkaitluParadisana("1");
    }//GEN-LAST:event_poga1ActionPerformed

    private void poga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga2ActionPerformed
        
       SkaitluParadisana("2");
    }//GEN-LAST:event_poga2ActionPerformed

    private void poga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga3ActionPerformed
        
        SkaitluParadisana("3");
    }//GEN-LAST:event_poga3ActionPerformed

    private void poga4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga4ActionPerformed
        
        SkaitluParadisana("4");
    }//GEN-LAST:event_poga4ActionPerformed

    private void poga5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga5ActionPerformed
        
        SkaitluParadisana("5");
    }//GEN-LAST:event_poga5ActionPerformed

    private void poga6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga6ActionPerformed
        
        SkaitluParadisana("6");
    }//GEN-LAST:event_poga6ActionPerformed

    private void poga7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga7ActionPerformed
        
        SkaitluParadisana("7");
    }//GEN-LAST:event_poga7ActionPerformed

    private void poga8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga8ActionPerformed
       
        SkaitluParadisana("8");
    }//GEN-LAST:event_poga8ActionPerformed

    private void poga9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga9ActionPerformed
        
        SkaitluParadisana("9");
    }//GEN-LAST:event_poga9ActionPerformed

    private void poga0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poga0ActionPerformed
        
        SkaitluParadisana("0");
    }//GEN-LAST:event_poga0ActionPerformed

    private void pogaequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogaequalActionPerformed
        if(darbiba){
            int skaitlis1 = Integer.valueOf(pirmaisSkaitlis);
            int skaitlis2 = Integer.valueOf(Laukums.getText());
            
            Aprekins rekins = new Aprekins();
            Laukums.setText(rekins.Aprekinat(skaitlis1, skaitlis2, zime));
            darbiba= false;
            zime = "";
        }
    }//GEN-LAST:event_pogaequalActionPerformed

    private void pogaplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogaplusActionPerformed
        pirmaisSkaitlis = Laukums.getText();
        darbiba = true;
        zime = "+";
        Laukums.setText("+");
    }//GEN-LAST:event_pogaplusActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        // TODO add your handling code here:
        pirmaisSkaitlis = Laukums.getText();
        darbiba = true;
        zime = "-";
        Laukums.setText("-");
    }//GEN-LAST:event_MinusActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Laukums.setText("0");
    }//GEN-LAST:event_ClearActionPerformed

    private void KapinasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapinasanaActionPerformed
        pirmaisSkaitlis = Laukums.getText();
        darbiba = true;
        zime = "^";
        Laukums.setText("^");
                
    }//GEN-LAST:event_KapinasanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Kapinasana;
    private javax.swing.JLabel Laukums;
    private javax.swing.JButton Minus;
    private javax.swing.JButton poga0;
    private javax.swing.JButton poga1;
    private javax.swing.JButton poga2;
    private javax.swing.JButton poga3;
    private javax.swing.JButton poga4;
    private javax.swing.JButton poga5;
    private javax.swing.JButton poga6;
    private javax.swing.JButton poga7;
    private javax.swing.JButton poga8;
    private javax.swing.JButton poga9;
    private javax.swing.JButton pogaequal;
    private javax.swing.JButton pogaplus;
    // End of variables declaration//GEN-END:variables
}
